### ISSUE TITLE
support for other regions?

### ISSUE THREAD

**Issue by Suburbanno** [NorthWebSolutions/Aram#10]

**Comment by gaboreszaki** [comment]
**Sorry for the late answer.**
Yes, I already planned a multi API connector.
The project in testing stage so I didn't permit all regions.
but **_a few days ago RIOT made some changes in the API system_** to make things a bit compatible with all region. so I will dig a bit to correct the interface.

**if you want, I can add your region manually to the BETA testers site, just let me know.**
(http://aram.northweb.co.uk/Login/index)

regards

**Comment by Suburbanno** [comment]
server  BR

**Comment by gaboreszaki** [comment]
hi, I **added your server** _**(BR)**_ to the registration menu, please try it. 
**if something didn't work please let me know**

**Comment by Suburbanno** [comment]
ok

**Comment by gaboreszaki** [comment]
next upcoming version will support all regions. :)
